### ISSUE TITLE
MATERIAL PARA REACT.JS

### ISSUE THREAD

**Issue by ghost** [react-brasil/react-sp#1]
Pessoal, estou querendo começar na area de React.js e gostaria que me enviassem links de diversos materiais que ajudam bastante.
Obrigado

**Comment by sibelius** [comment]
o ideal é entender o conceito de componentes

diferença entre `props` e `state`

https://facebook.github.io/react/docs/tutorial.html

**Comment by ronal2do** [comment]
Estava lendo isso agora achei muito bacana.

https://github.com/ericdouglas/traduz-ai/blob/master/react/02-introducao-ao-react-para-pessoas-que-sabem-apenas-jquery.md

e este em vídeos
http://kodezilla.com/courses/introducao-ao-react

**Comment by lucasbento** [comment]
Também temos [essa bela answer](https://github.com/react-sp/react-native-dojo/issues/14#issuecomment-183443484) do @sibelius em um outro projeto da organização.
